function(input, output) {
  output$selected_var <- renderText({ 
    paste("You have selected", input$selection)
  })
  output$probability_enrollment <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_enrollment * glm.ridge.coef$Enrollment[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_asian <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_asian * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Enrollment) * glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_black <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$black * glm.ridge.coef$black[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Enrollment)*glm.ridge.coef$Percent.Enrollment[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_principal <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_principal * glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_economic <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_economic * glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_instruction <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_instruction * glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_teachers <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_teachers*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Enrollment) * glm.ridge.coef$Enrollment[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] +  mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_supportive <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_supportive * glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_leadership <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_leadership * glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_community <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_community * glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_trust <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_trust * glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_esl <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_esl * glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_swd <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_swd * glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_selfcontained <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_selfcontained * glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_undercredited <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_undercredited * glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_hispanic <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_hispanic * glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_white <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_white * glm.ridge.coef$Percent.White[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_studentattendance <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_studentattendance * glm.ridge.coef$Student.Attendance.Rate[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]]), 3)) 
  })
  output$probability_teacherattendance <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_teacherattendance * glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$enrollment_plot <- renderPlot(p_enrollment + geom_vline(xintercept = input$slider_enrollment, colour = "blue", size = 1))
  output$asian_plot <- renderPlot(p_asian + geom_vline(xintercept = input$slider_asian, colour = "blue", size = 1))
  output$black_plot <- renderPlot(p_black + geom_vline(xintercept = input$slider_black, colour = "blue", size = 1))
  output$principal_plot <- renderPlot(p_principal_exp + geom_vline(xintercept = input$slider_principal, colour = "blue", size = 1))
  output$economic_plot <- renderPlot(p_econ + geom_vline(xintercept = input$slider_economic, colour = "blue", size = 1))
  output$instruction_plot <- renderPlot(p_instruction_rating + geom_vline(xintercept = input$slider_instruction, colour = "blue", size = 1))
  output$teachers_plot <- renderPlot(p_teachers + geom_vline(xintercept = input$slider_teachers, colour = "blue", size = 1))
  output$supportive_plot <- renderPlot(p_supportive + geom_vline(xintercept = input$slider_supportive, colour = "blue", size = 1))
  output$leadership_plot <- renderPlot(p_leadership + geom_vline(xintercept = input$slider_leadership, colour = "blue", size = 1))
  output$community_plot <- renderPlot(p_community + geom_vline(xintercept = input$slider_community, colour = "blue", size = 1))
  output$trust_plot <- renderPlot(p_trust + geom_vline(xintercept = input$slider_trust, colour = "blue", size = 1))
  output$esl_plot <- renderPlot(p_esl + geom_vline(xintercept = input$slider_esl, colour = "blue", size = 1))
  output$swd_plot <- renderPlot(p_swd + geom_vline(xintercept = input$slider_swd, colour = "blue", size = 1))
  output$selfcontained_plot <- renderPlot(p_selfcontained + geom_vline(xintercept = input$slider_selfcontained, colour = "blue", size = 1))
  output$undercredited_plot <- renderPlot(p_undercredited + geom_vline(xintercept = input$slider_undercredited, colour = "blue", size = 1))
  output$hispanic_plot <- renderPlot(p_hispanic + geom_vline(xintercept = input$slider_hispanic, colour = "blue", size = 1))
  output$white_plot <- renderPlot(p_white + geom_vline(xintercept = input$slider_white, colour = "blue", size = 1))
  output$studentattendance_plot <- renderPlot(p_studentattendance + geom_vline(xintercept = input$slider_studentattendance, colour = "blue", size = 1))
  output$teacherattendance_plot <- renderPlot(p_teacherattendance + geom_vline(xintercept = input$slider_teacherattendance, colour = "blue", size = 1))
  output$plot_explanation <- renderText({
    paste("This plot compares the distribution of schools that have met versus not met the target with respect to the parameter chosen. The blue vertical line indicates the parameter level that you have indicated.")
  })
}

library(rsconnect)
deployApp()

