---
title: "Shiny"
author: "Austin Jia"
date: "12/5/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ui = fluidPage(
  title = "NYC High School Performance",
  titlePanel("NYC High School Performance"),
  sidebarLayout(
    sidebarPanel = sidebarPanel(
      h4("Viewable Statistics"),
      helpText("View how changing school parameters affects whether it does or doesn't meet standards"),
      selectInput("selection", "Select something", choices = c("School Size", "Teachers Rating", "Supportive Environment", "Leadership", "Community Ties", "Trust", "Percent English Language Learners", "Percent Students with Disabilities", "Percent Self-Contained Classrooms", "Percent Undercredited" , "Race - Asian", "Race - Black", "Race - Hispanic", "Race - White","Economic Need Index", "Principal Experience", "Instruction Rating", "Student Attendance Rate", "Teacher Attendance Rate")),
      conditionalPanel(
        "input.selection == 'School Size'",
        sliderInput("slider_enrollment", "Enrollment", min = min(data5$Enrollment), max = max(data5$Enrollment), value = 100, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Race - Asian'",
        sliderInput("slider_asian", "Asian Percentage", min = min(data5$Percent.Asian), max = max(data5$Percent.Asian), value = 50, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Race - Black'",
        sliderInput("slider_black", "Black Percentage", min = min(data5$Percent.Black), max = max(data5$Percent.Black), value = 50, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Economic Need Index'",
        sliderInput("slider_economic", "Economic Need Index", min = min(data5$Economic.Need.Index), max = max(data5$Economic.Need.Index), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Principal Experience'",
        sliderInput("slider_principal", "Principal Experience", min = min(data5$Principal.Experience.yrs), max = max(data5$Principal.Experience.yrs), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Instruction Rating'",
        sliderInput("slider_instruction", "Percent Approval of Instruction", min = min(data5$Instruction.Rating.pct), max = max(data5$Instruction.Rating.pct), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Teachers Rating'",
        sliderInput("slider_teachers", "Percent Approval of Teachers", min = min(data5$Teachers.Rating.pct), max = max(data5$Teachers.Rating.pct), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Supportive Environment'",
        sliderInput("slider_supportive", "Percent Approval that School Environment is Supportive", min = min(data5$Supportive.Environment.pct), max = max(data5$Supportive.Environment.pct), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Leadership'",
        sliderInput("slider_leadership", "Percent Approval of Leadership in School", min = min(data5$Leadership.Rating.pct), max = max(data5$Leadership.Rating.pct), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Community Ties'",
        sliderInput("slider_community", "Percent Belief that school has strong community ties", min = min(data5$Community.Ties.Rating.pct), max = max(data5$Community.Ties.Rating.pct), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Trust'",
        sliderInput("slider_trust", "Percent Approval in Trust of School", min = min(data5$Trust...Percent.Positive), max = max(data5$Trust...Percent.Positive), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Percent English Language Learners'",
        sliderInput("slider_esl", "Percent English Language Learners", min = min(data5$Percent.English.Language.Learners), max = max(data5$Percent.English.Language.Learners), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Percent Students with Disabilities'",
        sliderInput("slider_swd", "Percent Students with Disabilities", min = min(data5$Percent.Students.with.Disabilities), max = max(data5$Percent.Students.with.Disabilities), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Percent Self-Contained Classrooms'",
        sliderInput("slider_selfcontained", "Percent Self-Contained Classrooms", min = min(data5$Trust...Percent.Positive), max = max(data5$Trust...Percent.Positive), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Percent Undercredited'",
        sliderInput("slider_undercredited", "Percent Undercredited", min = min(data5$Percent.Overage..Undercredited), max = max(data5$Percent.Overage..Undercredited), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Race - Hispanic'",
        sliderInput("slider_hispanic", "Percent Hispanic", min = min(data5$Percent.Hispanic), max = max(data5$Percent.Hispanic), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Race - White'",
        sliderInput("slider_white", "Percent White", min = min(data5$Percent.White), max = max(data5$Percent.White), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Student Attendance Rate'",
        sliderInput("slider_studentattendance", "Student Attendance Rate", min = min(data5$Student.Attendance.Rate), max = max(data5$Student.Attendance.Rate), value = .5, ticks = FALSE)
      ),
      conditionalPanel(
        "input.selection == 'Teacher Attendance Rate'",
        sliderInput("slider_teacherattendance", "Teacher Attendance Rate", min = min(data5$Trust...Percent.Positive), max = max(data5$Trust...Percent.Positive), value = .5, ticks = FALSE)
      )
    ),
    mainPanel = mainPanel(
      textOutput("selected_var"),
      conditionalPanel(
        condition = "input.selection == 'School Size'",
        textOutput("probability_enrollment")
      ),
      conditionalPanel(
        condition = "input.selection == 'Race - Asian'",
        textOutput("probability_asian")
      ),
      conditionalPanel(
        condition = "input.selection == 'Race - Black'",
        textOutput("probability_black")
      ),
      conditionalPanel(
        condition = "input.selection == 'Principal Experience'",
        textOutput("probability_principal")
      ),
      conditionalPanel(
        condition = "input.selection == 'Economic Need Index'",
        textOutput("probability_economic")
      ),
      conditionalPanel(
        condition = "input.selection == 'Instruction Rating'",
        textOutput("probability_instruction")
      ),
      conditionalPanel(
        condition = "input.selection == 'Teachers Rating'",
        textOutput("probability_teachers")
      ),
      conditionalPanel(
        condition = "input.selection == 'Supportive Environment'",
        textOutput("probability_supportive")
      ),
      conditionalPanel(
        condition = "input.selection == 'Leadership'",
        textOutput("probability_leadership")
      ),
      conditionalPanel(
        condition = "input.selection == 'Community Ties'",
        textOutput("probability_community")
      ),
      conditionalPanel(
        condition = "input.selection == 'Trust'",
        textOutput("probability_trust")
      ),
      conditionalPanel(
        condition = "input.selection == 'Percent English Language Learners'",
        textOutput("probability_esl")
      ),
      conditionalPanel(
        condition = "input.selection == 'Percent Students with Disabilities'",
        textOutput("probability_swd")
      ),
      conditionalPanel(
        condition = "input.selection == 'Percent Self-Contained Classrooms'",
        textOutput("probability_selfcontained")
      ),
      conditionalPanel(
        condition = "input.selection == 'Percent Undercredited'",
        textOutput("probability_undercredited")
      ),
      conditionalPanel(
        condition = "input.selection == 'Race - Hispanic'",
        textOutput("probability_hispanic")
      ),
      conditionalPanel(
        condition = "input.selection == 'Race - White'",
        textOutput("probability_white")
      ),
      conditionalPanel(
        condition = "input.selection == 'Student Attendance Rate'",
        textOutput("probability_studentattendance")
      ),
      conditionalPanel(
        condition = "input.selection == 'Teacher Attendance Rate'",
        textOutput("probability_teacherattendance")
      ),
      conditionalPanel(
        condition = "input.selection == 'School Size'",
        plotOutput("enrollment_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Race - Asian'",
        plotOutput("asian_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Race - Black'",
        plotOutput("black_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Principal Experience'",
        plotOutput("principal_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Economic Need Index'",
        plotOutput("economic_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Instruction Rating'",
        plotOutput("instruction_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Teachers Rating'",
        plotOutput("teachers_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Supportive Environment'",
        plotOutput("supportive_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Leadership'",
        plotOutput("leadership_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Community Ties'",
        plotOutput("community_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Trust'",
        plotOutput("trust_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Percent English Language Learners'",
        plotOutput("esl_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Percent Students with Disabilities'",
        plotOutput("swd_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Percent Self-Contained Classrooms'",
        plotOutput("selfcontained_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Percent Undercredited'",
        plotOutput("undercredited_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Race - Hispanic'",
        plotOutput("hispanic_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Race - White'",
        plotOutput("white_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Student Attendance Rate'",
        plotOutput("studentattendance_plot")
      ),
      conditionalPanel(
        condition = "input.selection == 'Teacher Attendance Rate'",
        plotOutput("teacherattendance_plot")
      ),
      textOutput("plot_explanation")
    )
  )
)

server = function(input, output) {
  output$selected_var <- renderText({ 
    paste("You have selected", input$selection)
  })
  output$probability_enrollment <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_enrollment * glm.ridge.coef$Enrollment[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_asian <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_asian * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Enrollment) * glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_black <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$black * glm.ridge.coef$black[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Enrollment)*glm.ridge.coef$Percent.Enrollment[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_principal <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_principal * glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_economic <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_economic * glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_instruction <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_instruction * glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_teachers <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_teachers*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Enrollment) * glm.ridge.coef$Enrollment[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] +  mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_supportive <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_supportive * glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_leadership <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_leadership * glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_community <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_community * glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_trust <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_trust * glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_esl <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_esl * glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_swd <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_swd * glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_selfcontained <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_selfcontained * glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_undercredited <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_undercredited * glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_hispanic <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_hispanic * glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_white <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_white * glm.ridge.coef$Percent.White[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$probability_studentattendance <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_studentattendance * glm.ridge.coef$Student.Attendance.Rate[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Teacher.Attendance.Rate)*glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]]), 3)) 
  })
  output$probability_teacherattendance <- renderText({ 
    paste("Holding all else equal, this school has a probability of meeting the target of", round(logit2prob(glm.ridge.coef$Intercept[[1]] + input$slider_teacherattendance * glm.ridge.coef$Teacher.Attendance.Rate[[1]] + mean(data5$Instruction.Rating.pct)*glm.ridge.coef$Instruction.Rating.pct[[1]] + mean(data5$Supportive.Environment.pct)*glm.ridge.coef$Supportive.Environment.pct[[1]] + mean(data5$Community.Ties.Rating.pct)*glm.ridge.coef$Community.Ties.Rating.pct[[1]] + mean(data5$Percent.English.Language.Learners)*glm.ridge.coef$Percent.English.Language.Learners[[1]] + mean(data5$Percent.Self.Contained)*glm.ridge.coef$Percent.Self.Contained[[1]] + mean(data5$Percent.Overage..Undercredited)*glm.ridge.coef$Percent.Overage..Undercredited[[1]] + mean(data5$Percent.Asian) * glm.ridge.coef$Percent.Asian[[1]] + mean(data5$Percent.Black)*glm.ridge.coef$Percent.Black[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Percent.Hispanic)*glm.ridge.coef$Percent.Hispanic[[1]] + mean(data5$Percent.White)*glm.ridge.coef$Percent.White[[1]] + mean(data5$Teachers.3yrs.Experience)*glm.ridge.coef$Teachers.3yrs.Experience[[1]] + mean(data5$Enrollment)*glm.ridge.coef$Enrollment[[1]] + mean(data5$Teachers.Rating.pct)*glm.ridge.coef$Teachers.Rating.pct[[1]] + mean(data5$Leadership.Rating.pct)*glm.ridge.coef$Leadership.Rating.pct[[1]] + mean(data5$Trust...Percent.Positive)*glm.ridge.coef$Trust...Percent.Positive[[1]] + mean(data5$Percent.Students.with.Disabilities)*glm.ridge.coef$Percent.Students.with.Disabilities[[1]] + mean(data5$Economic.Need.Index)*glm.ridge.coef$Economic.Need.Index[[1]] + mean(data5$Principal.Experience.yrs)*glm.ridge.coef$Principal.Experience.yrs[[1]] + mean(data5$Student.Attendance.Rate)*glm.ridge.coef$Student.Attendance.Rate[[1]]), 3)) 
  })
  output$enrollment_plot <- renderPlot(p_enrollment + geom_vline(aes(xintercept = input$slider_enrollment), colour = "blue", size = 1))
  output$asian_plot <- renderPlot(p_asian + geom_vline(aes(xintercept = input$slider_asian), colour = "blue", size = 1))
  output$black_plot <- renderPlot(p_black + geom_vline(aes(xintercept = input$slider_black), colour = "blue", size = 1))
  output$principal_plot <- renderPlot(p_principal_exp + geom_vline(aes(xintercept = input$slider_principal), colour = "blue", size = 1))
  output$economic_plot <- renderPlot(p_econ + geom_vline(aes(xintercept = input$slider_economic), colour = "blue", size = 1))
  output$instruction_plot <- renderPlot(p_instruction_rating + geom_vline(aes(xintercept = input$slider_instruction), colour = "blue", size = 1))
  output$teachers_plot <- renderPlot(p_teachers + geom_vline(aes(xintercept = input$slider_teachers), colour = "blue", size = 1))
  output$supportive_plot <- renderPlot(p_supportive + geom_vline(aes(xintercept = input$slider_supportive), colour = "blue", size = 1))
  output$leadership_plot <- renderPlot(p_leadership + geom_vline(aes(xintercept = input$slider_leadership), colour = "blue", size = 1))
  output$community_plot <- renderPlot(p_community + geom_vline(aes(xintercept = input$slider_community), colour = "blue", size = 1))
  output$trust_plot <- renderPlot(p_trust + geom_vline(aes(xintercept = input$slider_trust), colour = "blue", size = 1))
  output$esl_plot <- renderPlot(p_esl + geom_vline(aes(xintercept = input$slider_esl), colour = "blue", size = 1))
  output$swd_plot <- renderPlot(p_swd + geom_vline(aes(xintercept = input$slider_swd), colour = "blue", size = 1))
  output$selfcontained_plot <- renderPlot(p_selfcontained + geom_vline(aes(xintercept = input$slider_selfcontained), colour = "blue", size = 1))
  output$undercredited_plot <- renderPlot(p_undercredited + geom_vline(aes(xintercept = input$slider_undercredited), colour = "blue", size = 1))
  output$hispanic_plot <- renderPlot(p_hispanic + geom_vline(aes(xintercept = input$slider_hispanic), colour = "blue", size = 1))
  output$white_plot <- renderPlot(p_white + geom_vline(aes(xintercept = input$slider_white), colour = "blue", size = 1))
  output$studentattendance_plot <- renderPlot(p_studentattendance + geom_vline(aes(xintercept = input$slider_studentattendance), colour = "blue", size = 1))
  output$teacherattendance_plot <- renderPlot(p_teacherattendance + geom_vline(aes(xintercept = input$slider_teacherattendance), colour = "blue", size = 1))
  output$plot_explanation <- renderText({
    paste("This plot compares the distribution of schools that have met versus not met the target with respect to the parameter chosen. The blue vertical line indicates the parameter level that you have indicated.")
  })
}

shinyApp(ui, server)
```

